services:
  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=10G
      - APACHE_SERVERNAME=homeserver25.kozow.com
    networks:
      - proxy-net

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - proxy-net

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASS}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - LC_ALL=C.UTF-8
    volumes:
      - /mnt/storage/media/nextcloud/data:/var/www/html
      - /mnt/storage/media/nextcloud/userdata:/var/www/html/data
      - /srv/logs/nextcloud/nextcloud.log:/var/www/html/data/nextcloud.log
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
        apt-get update
        apt-get install -y \
          tesseract-ocr tesseract-ocr-heb tesseract-ocr-rus \
          libreoffice \
          fonts-liberation fonts-noto-core fonts-noto-ui-core fonts-noto-extra \
          ttf-mscorefonts-installer
        /entrypoint.sh apache2-foreground
    networks:
      - proxy-net

  notify_push:
    image: ghcr.io/nextcloud/notify_push:latest
    container_name: nextcloud-push
    restart: always
    environment:
      - PORT=7867
      - NEXTCLOUD_URL=${NCURL}
    command: /notify_push /var/www/html/config/config.php
    volumes:
      - /mnt/storage/media/nextcloud/data:/var/www/html:ro
    networks:
      - proxy-net
    depends_on:
      - app
      - redis
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/storage/media/nextcloud/elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true